name: com-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - matplotlib
  - sympy
  - numba
  - pip:
    - jitcode
    - jitcdde
    - jitcsde
    - jitcxde-common